runtime: python310

entrypoint: python main.py

env_variables:
  SECRET_KEY: "sahayak-production-key-2025"
  GOOGLE_API_KEY: "AIzaSyAI2G2R9VxNF7RqgchmKRK-acGo9ip7lyU"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: static